### PR TITLE
check foldGutter for exists

### PR DESCRIPTION
**Pull request by mloginov**

### CODE REVIEW

**Comment by Dignifiedquire** [comment]
Looks good to me. Is there a PR to the main CodeMirror repo?

**Comment by mloginov** [comment]
Just created https://github.com/codemirror/CodeMirror/pull/3071

**Comment by joelmoss** [comment]
@mloginov what is the status of this?

**Comment by mloginov** [comment]
Not needed already. Fixed in main CM repo.

**Pull request closed without merging**
